services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx:hive
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_pages:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env
      
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress:hive
    volumes:
      - wp_pages:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
      
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb:hive
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/database
      o: bind
  wp_pages:
    name: wp_pages
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wp_pages
      o: bind

networks:
  inception:
    name: inception
    driver: bridge